### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [e-sr/moonboard#14]
I am currently working on a fork with WS2811 LED fixes, installation simplification etc. Could you clarify the license of your code? I'd like to share my contributions under GPL 3. 

Regards 
Gerolf

**Comment by e-sr** [comment]
Hi, I have never look exactly wich license is best suited, feel it free to make a PR with the most suited license I will accept.

**Comment by 8cH9azbsFifZ** [comment]
You have created a very good open source project. If sharing potential improvements is important to you, then we should go for [GPLv3](https://choosealicense.com/). The GNU GPLv3 also lets people do almost anything they want with your project, except distributing closed source versions.

In contrast the MIT license for example lets people do almost anything they want with your project, like making and distributing closed source versions. This is probably not what you want (as there is already a closed source implementation by the inventors at moonboard.

I would go for the GPVv3.

**Comment by e-sr** [comment]
I will also add the license you suggested. Thank you
